from tkinter import *
from tkinter import ttk
#import math, Pokedex, MetaDex, Tools, threading, random, datetime, os, glob
#import urllib.request

class TeamAnalyzer:

    def __init__(self,root):
        root.title("Team Analyzer")
        root.geometry("870x700")
        offCovFrame = Frame(root)
        offCovFrame.pack(side=LEFT,fill=Y)
        Label(offCovFrame, text="Offensive Coverage").grid(row=0, column=0, columnspan=11,sticky=EW)
        ttk.Separator(offCovFrame, orient=HORIZONTAL).grid(row=1, column=3, columnspan=7, sticky=EW)
        ttk.Separator(offCovFrame, orient=HORIZONTAL).grid(row=3, column=1, columnspan=10, sticky=EW)
        ttk.Separator(offCovFrame, orient=HORIZONTAL).grid(row=22, column=1, columnspan=10, sticky=EW)
        ttk.Separator(offCovFrame, orient=VERTICAL).grid(row=4, column=0, rowspan=18, sticky=NS, padx=(10,0))
        ttk.Separator(offCovFrame, orient=VERTICAL).grid(row=2, column=2, rowspan=20, sticky=NS)
        ttk.Separator(offCovFrame, orient=VERTICAL).grid(row=2, column=4, rowspan=20, sticky=NS)
        ttk.Separator(offCovFrame, orient=VERTICAL).grid(row=2, column=6, rowspan=20, sticky=NS)
        ttk.Separator(offCovFrame, orient=VERTICAL).grid(row=2, column=8, rowspan=20, sticky=NS)
        ttk.Separator(offCovFrame, orient=VERTICAL).grid(row=2, column=10, rowspan=20, sticky=NS)

        Label(offCovFrame, text="0").grid(row=2, column=3, padx=10)
        Label(offCovFrame, text="1/2").grid(row=2, column=5, padx=5)
        Label(offCovFrame, text="1").grid(row=2, column=7, padx=10)
        Label(offCovFrame, text="2").grid(row=2, column=9, padx=10)

        Label(offCovFrame, text="Normal", anchor=W).grid(row=4, column=1, pady=1)
        self.normalzeroOffText = StringVar()
        self.normalzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.normalzeroOffText, anchor=W).grid(row=4, column=3)
        self.normalhalfOffText = StringVar()
        self.normalhalfOffText.set("0")
        Label(offCovFrame, textvariable=self.normalhalfOffText, anchor=W).grid(row=4, column=5)
        self.normaloneOffText = StringVar()
        self.normaloneOffText.set("0")
        Label(offCovFrame, textvariable=self.normaloneOffText, anchor=W).grid(row=4, column=7)
        self.normaltwoOffOffText = StringVar()
        self.normaltwoOffOffText.set("0")
        Label(offCovFrame, textvariable=self.normaltwoOffOffText, anchor=W).grid(row=4, column=9)

        Label(offCovFrame, text="Fire", anchor=W).grid(row=5, column=1, pady=1)
        self.firezeroOffText = StringVar()
        self.firezeroOffText.set("0")
        Label(offCovFrame, textvariable=self.firezeroOffText, anchor=W).grid(row=5, column=3)
        self.firehalfOffText = StringVar()
        self.firehalfOffText.set("0")
        Label(offCovFrame, textvariable=self.firehalfOffText, anchor=W).grid(row=5, column=5)
        self.fireoneOffText = StringVar()
        self.fireoneOffText.set("0")
        Label(offCovFrame, textvariable=self.fireoneOffText, anchor=W).grid(row=5, column=7)
        self.firetwoOffOffText = StringVar()
        self.firetwoOffOffText.set("0")
        Label(offCovFrame, textvariable=self.firetwoOffOffText, anchor=W).grid(row=5, column=9)

        Label(offCovFrame, text="Water", anchor=W).grid(row=6, column=1, pady=1)
        self.waterzeroOffText = StringVar()
        self.waterzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.waterzeroOffText, anchor=W).grid(row=6, column=3)
        self.waterhalfOffText = StringVar()
        self.waterhalfOffText.set("0")
        Label(offCovFrame, textvariable=self.waterhalfOffText, anchor=W).grid(row=6, column=5)
        self.wateroneOffText = StringVar()
        self.wateroneOffText.set("0")
        Label(offCovFrame, textvariable=self.wateroneOffText, anchor=W).grid(row=6, column=7)
        self.watertwoOffOffText = StringVar()
        self.watertwoOffOffText.set("0")
        Label(offCovFrame, textvariable=self.watertwoOffOffText, anchor=W).grid(row=6, column=9)

        Label(offCovFrame, text="Electric", anchor=W).grid(row=7, column=1, pady=1)
        self.electriczeroOffText = StringVar()
        self.electriczeroOffText.set("0")
        Label(offCovFrame, textvariable=self.electriczeroOffText, anchor=W).grid(row=7, column=3)
        self.electrichalfOffText = StringVar()
        self.electrichalfOffText.set("0")
        Label(offCovFrame, textvariable=self.electrichalfOffText, anchor=W).grid(row=7, column=5)
        self.electriconeOffText = StringVar()
        self.electriconeOffText.set("0")
        Label(offCovFrame, textvariable=self.electriconeOffText, anchor=W).grid(row=7, column=7)
        self.electrictwoOffOffText = StringVar()
        self.electrictwoOffOffText.set("0")
        Label(offCovFrame, textvariable=self.electrictwoOffOffText, anchor=W).grid(row=7, column=9)

        Label(offCovFrame, text="Grass", anchor=W).grid(row=8, column=1, pady=1)
        self.grasszeroOffText = StringVar()
        self.grasszeroOffText.set("0")
        Label(offCovFrame, textvariable=self.grasszeroOffText, anchor=W).grid(row=8, column=3)
        self.grasshalfOffText = StringVar()
        self.grasshalfOffText.set("0")
        Label(offCovFrame, textvariable=self.grasshalfOffText, anchor=W).grid(row=8, column=5)
        self.grassoneOffText = StringVar()
        self.grassoneOffText.set("0")
        Label(offCovFrame, textvariable=self.grassoneOffText, anchor=W).grid(row=8, column=7)
        self.grasstwoOffOffText = StringVar()
        self.grasstwoOffOffText.set("0")
        Label(offCovFrame, textvariable=self.grasstwoOffOffText, anchor=W).grid(row=8, column=9)

        Label(offCovFrame, text="Ice", anchor=W).grid(row=9, column=1, pady=1)
        self.icezeroOffText = StringVar()
        self.icezeroOffText.set("0")
        Label(offCovFrame, textvariable=self.icezeroOffText, anchor=W).grid(row=9, column=3)
        self.icehalfOffText = StringVar()
        self.icehalfOffText.set("0")
        Label(offCovFrame, textvariable=self.icehalfOffText, anchor=W).grid(row=9, column=5)
        self.iceoneOffText = StringVar()
        self.iceoneOffText.set("0")
        Label(offCovFrame, textvariable=self.iceoneOffText, anchor=W).grid(row=9, column=7)
        self.icetwoOffOffText = StringVar()
        self.icetwoOffOffText.set("0")
        Label(offCovFrame, textvariable=self.icetwoOffOffText, anchor=W).grid(row=9, column=9)

        Label(offCovFrame, text="Fighting", anchor=W).grid(row=10, column=1, pady=1)
        self.fightingzeroOffText = StringVar()
        self.fightingzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.fightingzeroOffText, anchor=W).grid(row=10, column=3)
        self.fightinghalfOffText = StringVar()
        self.fightinghalfOffText.set("0")
        Label(offCovFrame, textvariable=self.fightinghalfOffText, anchor=W).grid(row=10, column=5)
        self.fightingoneOffText = StringVar()
        self.fightingoneOffText.set("0")
        Label(offCovFrame, textvariable=self.fightingoneOffText, anchor=W).grid(row=10, column=7)
        self.fightingtwoOffOffText = StringVar()
        self.fightingtwoOffOffText.set("0")
        Label(offCovFrame, textvariable=self.fightingtwoOffOffText, anchor=W).grid(row=10, column=9)

        Label(offCovFrame, text="Poison", anchor=W).grid(row=11, column=1, pady=1)
        self.poisonzeroOffText = StringVar()
        self.poisonzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.poisonzeroOffText, anchor=W).grid(row=11, column=3)
        self.poisonhalfOffText = StringVar()
        self.poisonhalfOffText.set("0")
        Label(offCovFrame, textvariable=self.poisonhalfOffText, anchor=W).grid(row=11, column=5)
        self.poisononeOffText = StringVar()
        self.poisononeOffText.set("0")
        Label(offCovFrame, textvariable=self.poisononeOffText, anchor=W).grid(row=11, column=7)
        self.poisontwoOffText = StringVar()
        self.poisontwoOffText.set("0")
        Label(offCovFrame, textvariable=self.poisontwoOffText, anchor=W).grid(row=11, column=9)

        Label(offCovFrame, text="Ground", anchor=W).grid(row=12, column=1, pady=1)
        self.groundzeroOffText = StringVar()
        self.groundzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.groundzeroOffText, anchor=W).grid(row=12, column=3)
        self.groundhalfOffText = StringVar()
        self.groundhalfOffText.set("0")
        Label(offCovFrame, textvariable=self.groundhalfOffText, anchor=W).grid(row=12, column=5)
        self.groundoneOffText = StringVar()
        self.groundoneOffText.set("0")
        Label(offCovFrame, textvariable=self.groundoneOffText, anchor=W).grid(row=12, column=7)
        self.groundtwoOffText = StringVar()
        self.groundtwoOffText.set("0")
        Label(offCovFrame, textvariable=self.groundtwoOffText, anchor=W).grid(row=12, column=9)

        Label(offCovFrame, text="Flying", anchor=W).grid(row=13, column=1, pady=1)
        self.flyingzeroOffText = StringVar()
        self.flyingzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.flyingzeroOffText, anchor=W).grid(row=13, column=3)
        self.flyinghalfOffText = StringVar()
        self.flyinghalfOffText.set("0")
        Label(offCovFrame, textvariable=self.flyinghalfOffText, anchor=W).grid(row=13, column=5)
        self.flyingoneOffText = StringVar()
        self.flyingoneOffText.set("0")
        Label(offCovFrame, textvariable=self.flyingoneOffText, anchor=W).grid(row=13, column=7)
        self.flyingtwoOffText = StringVar()
        self.flyingtwoOffText.set("0")
        Label(offCovFrame, textvariable=self.flyingtwoOffText, anchor=W).grid(row=13, column=9)

        Label(offCovFrame, text="Psychic", anchor=W).grid(row=14, column=1, pady=1)
        self.psychiczeroOffText = StringVar()
        self.psychiczeroOffText.set("0")
        Label(offCovFrame, textvariable=self.psychiczeroOffText, anchor=W).grid(row=14, column=3)
        self.psychichalfOffText = StringVar()
        self.psychichalfOffText.set("0")
        Label(offCovFrame, textvariable=self.psychichalfOffText, anchor=W).grid(row=14, column=5)
        self.psychiconeOffText = StringVar()
        self.psychiconeOffText.set("0")
        Label(offCovFrame, textvariable=self.psychiconeOffText, anchor=W).grid(row=14, column=7)
        self.psychictwoOffText = StringVar()
        self.psychictwoOffText.set("0")
        Label(offCovFrame, textvariable=self.psychictwoOffText, anchor=W).grid(row=14, column=9)

        Label(offCovFrame, text="Bug", anchor=W).grid(row=15, column=1, pady=1)
        self.bugzeroOffText = StringVar()
        self.bugzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.bugzeroOffText, anchor=W).grid(row=15, column=3)
        self.bughalfOffText = StringVar()
        self.bughalfOffText.set("0")
        Label(offCovFrame, textvariable=self.bughalfOffText, anchor=W).grid(row=15, column=5)
        self.bugoneOffText = StringVar()
        self.bugoneOffText.set("0")
        Label(offCovFrame, textvariable=self.bugoneOffText, anchor=W).grid(row=15, column=7)
        self.bugtwoOffText = StringVar()
        self.bugtwoOffText.set("0")
        Label(offCovFrame, textvariable=self.bugtwoOffText, anchor=W).grid(row=15, column=9)

        Label(offCovFrame, text="Rock", anchor=W).grid(row=16, column=1, pady=1)
        self.rockzeroOffText = StringVar()
        self.rockzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.rockzeroOffText, anchor=W).grid(row=16, column=3)
        self.rockhalfOffText = StringVar()
        self.rockhalfOffText.set("0")
        Label(offCovFrame, textvariable=self.rockhalfOffText, anchor=W).grid(row=16, column=5)
        self.rockoneOffText = StringVar()
        self.rockoneOffText.set("0")
        Label(offCovFrame, textvariable=self.rockoneOffText, anchor=W).grid(row=16, column=7)
        self.rocktwoOffText = StringVar()
        self.rocktwoOffText.set("0")
        Label(offCovFrame, textvariable=self.rocktwoOffText, anchor=W).grid(row=16, column=9)

        Label(offCovFrame, text="Ghost", anchor=W).grid(row=17, column=1, pady=1)
        self.ghostzeroOffText = StringVar()
        self.ghostzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.ghostzeroOffText, anchor=W).grid(row=17, column=3)
        self.ghosthalfOffText = StringVar()
        self.ghosthalfOffText.set("0")
        Label(offCovFrame, textvariable=self.ghosthalfOffText, anchor=W).grid(row=17, column=5)
        self.ghostoneOffText = StringVar()
        self.ghostoneOffText.set("0")
        Label(offCovFrame, textvariable=self.ghostoneOffText, anchor=W).grid(row=17, column=7)
        self.ghosttwoOffText = StringVar()
        self.ghosttwoOffText.set("0")
        Label(offCovFrame, textvariable=self.ghosttwoOffText, anchor=W).grid(row=17, column=9)

        Label(offCovFrame, text="Dragon", anchor=W).grid(row=18, column=1, pady=1)
        self.dragonzeroOffText = StringVar()
        self.dragonzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.dragonzeroOffText, anchor=W).grid(row=18, column=3)
        self.dragonhalfOffText = StringVar()
        self.dragonhalfOffText.set("0")
        Label(offCovFrame, textvariable=self.dragonhalfOffText, anchor=W).grid(row=18, column=5)
        self.dragononeOffText = StringVar()
        self.dragononeOffText.set("0")
        Label(offCovFrame, textvariable=self.dragononeOffText, anchor=W).grid(row=18, column=7)
        self.dragontwoOffText = StringVar()
        self.dragontwoOffText.set("0")
        Label(offCovFrame, textvariable=self.dragontwoOffText, anchor=W).grid(row=18, column=9)

        Label(offCovFrame, text="Dark", anchor=W).grid(row=19, column=1, pady=1)
        self.darkzeroOffText = StringVar()
        self.darkzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.darkzeroOffText, anchor=W).grid(row=19, column=3)
        self.darkhalfOffText = StringVar()
        self.darkhalfOffText.set("0")
        Label(offCovFrame, textvariable=self.darkhalfOffText, anchor=W).grid(row=19, column=5)
        self.darkoneOffText = StringVar()
        self.darkoneOffText.set("0")
        Label(offCovFrame, textvariable=self.darkoneOffText, anchor=W).grid(row=19, column=7)
        self.darktwoOffText = StringVar()
        self.darktwoOffText.set("0")
        Label(offCovFrame, textvariable=self.darktwoOffText, anchor=W).grid(row=19, column=9)

        Label(offCovFrame, text="Steel", anchor=W).grid(row=20, column=1, pady=1)
        self.steelzeroOffText = StringVar()
        self.steelzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.steelzeroOffText, anchor=W).grid(row=20, column=3)
        self.steelhalfOffText = StringVar()
        self.steelhalfOffText.set("0")
        Label(offCovFrame, textvariable=self.steelhalfOffText, anchor=W).grid(row=20, column=5)
        self.steeloneOffText = StringVar()
        self.steeloneOffText.set("0")
        Label(offCovFrame, textvariable=self.steeloneOffText, anchor=W).grid(row=20, column=7)
        self.steeltwoOffText = StringVar()
        self.steeltwoOffText.set("0")
        Label(offCovFrame, textvariable=self.steeltwoOffText, anchor=W).grid(row=20, column=9)

        Label(offCovFrame, text="Fairy", anchor=W).grid(row=21, column=1, pady=1)
        self.fairyzeroOffText = StringVar()
        self.fairyzeroOffText.set("0")
        Label(offCovFrame, textvariable=self.fairyzeroOffText, anchor=W).grid(row=21, column=3)
        self.fairyhalfOffText = StringVar()
        self.fairyhalfOffText.set("0")
        Label(offCovFrame, textvariable=self.fairyhalfOffText, anchor=W).grid(row=21, column=5)
        self.fairyoneOffText = StringVar()
        self.fairyoneOffText.set("0")
        Label(offCovFrame, textvariable=self.fairyoneOffText, anchor=W).grid(row=21, column=7)
        self.fairytwoOffText = StringVar()
        self.fairytwoOffText.set("0")
        Label(offCovFrame, textvariable=self.fairytwoOffText, anchor=W).grid(row=21, column=9)

        middleFrame = Frame(root)
        middleFrame.pack(side=LEFT, fill=Y)
        Label(middleFrame,text="Physical/Special Balances").grid(row=0,column=0,columnspan=2,sticky=EW)
        Label(middleFrame,text="Offenive Balance").grid(row=1,column=0,columnspan=2,sticky=EW)
        physpecOffCanvas = Canvas(middleFrame, height=20)
        physpecOffCanvas.grid(row=2,column=0,columnspan=2,padx=10,sticky=EW)
        self.offBalance=50
        size=physpecOffCanvas.winfo_reqwidth()
        physpecOffCanvas.create_rectangle(0,0,self.offBalance,20,fill="orange red")
        physpecOffCanvas.create_rectangle(self.offBalance,0,size,20,fill="cornflower blue")

        Label(middleFrame, text="Defensive Balance").grid(row=3,column=0,columnspan=2,sticky=EW)
        self.physpecDefCanvas = Canvas(middleFrame, height=20)
        self.physpecDefCanvas.grid(row=4,column=0,columnspan=2,padx=10,sticky=EW)
        self.defBalance = 50
        self.physpecDefCanvas.create_rectangle(0, 0, self.defBalance, 20, fill="orange red")
        self.physpecDefCanvas.create_rectangle(self.defBalance, 0, size, 20, fill="cornflower blue")

        self.adviceMssngr = Text(middleFrame, wrap=WORD,width=45,height=21)
        self.adviceMssngr.grid(row=5,column=0,pady=10,padx=(10,0),sticky=EW)
        self.adviceMssngr.config(state=DISABLED)
        advicescrollbar = Scrollbar(middleFrame, command=self.adviceMssngr.yview)
        advicescrollbar.grid(row=5,column=1,padx=(0,10),pady=10,sticky=NS)
        self.adviceMssngr["yscrollcommand"] = advicescrollbar.set

        defCovFrame = Frame(root)
        defCovFrame.pack(side=LEFT,fill=Y)
        Label(defCovFrame, text="Defensive Coverage").grid(row=0, column=0, columnspan=15, sticky=EW)
        ttk.Separator(defCovFrame, orient=HORIZONTAL).grid(row=1, column=2, columnspan=12, sticky=EW)
        ttk.Separator(defCovFrame, orient=HORIZONTAL).grid(row=3, column=1, columnspan=13, sticky=EW)
        ttk.Separator(defCovFrame, orient=HORIZONTAL).grid(row=22, column=1, columnspan=13, sticky=EW)
        ttk.Separator(defCovFrame, orient=VERTICAL).grid(row=4, column=0, rowspan=18, sticky=NS)
        ttk.Separator(defCovFrame, orient=VERTICAL).grid(row=2, column=2, rowspan=20, sticky=NS)
        ttk.Separator(defCovFrame, orient=VERTICAL).grid(row=2, column=4, rowspan=20, sticky=NS)
        ttk.Separator(defCovFrame, orient=VERTICAL).grid(row=2, column=6, rowspan=20, sticky=NS)
        ttk.Separator(defCovFrame, orient=VERTICAL).grid(row=2, column=8, rowspan=20, sticky=NS)
        ttk.Separator(defCovFrame, orient=VERTICAL).grid(row=2, column=10, rowspan=20, sticky=NS)
        ttk.Separator(defCovFrame, orient=VERTICAL).grid(row=2, column=12, rowspan=20, sticky=NS)
        ttk.Separator(defCovFrame, orient=VERTICAL).grid(row=2, column=14, rowspan=20, sticky=NS,padx=(0,10))

        Label(defCovFrame, text="0").grid(row=2, column=3, padx=10)
        Label(defCovFrame, text="1/4").grid(row=2, column=5, padx=5)
        Label(defCovFrame, text="1/2").grid(row=2, column=7, padx=5)
        Label(defCovFrame, text="1").grid(row=2, column=9, padx=10)
        Label(defCovFrame, text="2").grid(row=2, column=11, padx=10)
        Label(defCovFrame, text="4").grid(row=2, column=13, padx=10)

        Label(defCovFrame, text="Normal", anchor=W).grid(row=4, column=1, pady=1)
        self.normalzeroDefText = StringVar()
        self.normalzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.normalzeroDefText, anchor=W).grid(row=4, column=3)
        self.normalquarterDefText = StringVar()
        self.normalquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.normalquarterDefText, anchor=W).grid(row=4,column=5)
        self.normalhalfDefText = StringVar()
        self.normalhalfDefText.set("0")
        Label(defCovFrame, textvariable=self.normalhalfDefText, anchor=W).grid(row=4, column=7)
        self.normaloneDefText = StringVar()
        self.normaloneDefText.set("0")
        Label(defCovFrame, textvariable=self.normaloneDefText, anchor=W).grid(row=4, column=9)
        self.normaltwoDefText = StringVar()
        self.normaltwoDefText.set("0")
        Label(defCovFrame, textvariable=self.normaltwoDefText, anchor=W).grid(row=4, column=11)
        self.normalfourDefText = StringVar()
        self.normalfourDefText.set("0")
        Label(defCovFrame, textvariable=self.normalfourDefText, anchor=W).grid(row=4, column=13)

        Label(defCovFrame, text="Fire", anchor=W).grid(row=5, column=1, pady=1)
        self.firezeroDefText = StringVar()
        self.firezeroDefText.set("0")
        Label(defCovFrame, textvariable=self.firezeroDefText, anchor=W).grid(row=5, column=3)
        self.firequarterDefText = StringVar()
        self.firequarterDefText.set("0")
        Label(defCovFrame, textvariable=self.firequarterDefText, anchor=W).grid(row=5,column=5)
        self.firehalfDefText = StringVar()
        self.firehalfDefText.set("0")
        Label(defCovFrame, textvariable=self.firehalfDefText, anchor=W).grid(row=5, column=7)
        self.fireoneDefText = StringVar()
        self.fireoneDefText.set("0")
        Label(defCovFrame, textvariable=self.fireoneDefText, anchor=W).grid(row=5, column=9)
        self.firetwoDefText = StringVar()
        self.firetwoDefText.set("0")
        Label(defCovFrame, textvariable=self.firetwoDefText, anchor=W).grid(row=5, column=11)
        self.firefourDefText = StringVar()
        self.firefourDefText.set("0")
        Label(defCovFrame, textvariable=self.firefourDefText, anchor=W).grid(row=5, column=13)

        Label(defCovFrame, text="Water", anchor=W).grid(row=6, column=1, pady=1)
        self.waterzeroDefText = StringVar()
        self.waterzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.waterzeroDefText, anchor=W).grid(row=6, column=3)
        self.waterquarterDefText = StringVar()
        self.waterquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.waterquarterDefText, anchor=W).grid(row=6,column=5)
        self.waterhalfDefText = StringVar()
        self.waterhalfDefText.set("0")
        Label(defCovFrame, textvariable=self.waterhalfDefText, anchor=W).grid(row=6, column=7)
        self.wateroneDefText = StringVar()
        self.wateroneDefText.set("0")
        Label(defCovFrame, textvariable=self.wateroneDefText, anchor=W).grid(row=6, column=9)
        self.watertwoDefText = StringVar()
        self.watertwoDefText.set("0")
        Label(defCovFrame, textvariable=self.watertwoDefText, anchor=W).grid(row=6, column=11)
        self.waterfourDefText = StringVar()
        self.waterfourDefText.set("0")
        Label(defCovFrame, textvariable=self.waterfourDefText, anchor=W).grid(row=6, column=13)

        Label(defCovFrame, text="Electric", anchor=W).grid(row=7, column=1, pady=1)
        self.electriczeroDefText = StringVar()
        self.electriczeroDefText.set("0")
        Label(defCovFrame, textvariable=self.electriczeroDefText, anchor=W).grid(row=7, column=3)
        self.electricquarterDefText = StringVar()
        self.electricquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.electricquarterDefText, anchor=W).grid(row=7,column=5)
        self.electrichalfDefText = StringVar()
        self.electrichalfDefText.set("0")
        Label(defCovFrame, textvariable=self.electrichalfDefText, anchor=W).grid(row=7, column=7)
        self.electriconeDefText = StringVar()
        self.electriconeDefText.set("0")
        Label(defCovFrame, textvariable=self.electriconeDefText, anchor=W).grid(row=7, column=9)
        self.electrictwoDefText = StringVar()
        self.electrictwoDefText.set("0")
        Label(defCovFrame, textvariable=self.electrictwoDefText, anchor=W).grid(row=7, column=11)
        self.electricfourDefText = StringVar()
        self.electricfourDefText.set("0")
        Label(defCovFrame, textvariable=self.electricfourDefText, anchor=W).grid(row=7, column=13)

        Label(defCovFrame, text="Grass", anchor=W).grid(row=8, column=1, pady=1)
        self.grasszeroDefText = StringVar()
        self.grasszeroDefText.set("0")
        Label(defCovFrame, textvariable=self.grasszeroDefText, anchor=W).grid(row=8, column=3)
        self.grassquarterDefText = StringVar()
        self.grassquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.grassquarterDefText, anchor=W).grid(row=8,column=5)
        self.grasshalfDefText = StringVar()
        self.grasshalfDefText.set("0")
        Label(defCovFrame, textvariable=self.grasshalfDefText, anchor=W).grid(row=8, column=7)
        self.grassoneDefText = StringVar()
        self.grassoneDefText.set("0")
        Label(defCovFrame, textvariable=self.grassoneDefText, anchor=W).grid(row=8, column=9)
        self.grasstwoDefText = StringVar()
        self.grasstwoDefText.set("0")
        Label(defCovFrame, textvariable=self.grasstwoDefText, anchor=W).grid(row=8, column=11)
        self.grassfourDefText = StringVar()
        self.grassfourDefText.set("0")
        Label(defCovFrame, textvariable=self.grassfourDefText, anchor=W).grid(row=8, column=13)

        Label(defCovFrame, text="Ice", anchor=W).grid(row=9, column=1, pady=1)
        self.icezeroDefText = StringVar()
        self.icezeroDefText.set("0")
        Label(defCovFrame, textvariable=self.icezeroDefText, anchor=W).grid(row=9, column=3)
        self.icequarterDefText = StringVar()
        self.icequarterDefText.set("0")
        Label(defCovFrame, textvariable=self.icequarterDefText, anchor=W).grid(row=9,column=5)
        self.icehalfDefText = StringVar()
        self.icehalfDefText.set("0")
        Label(defCovFrame, textvariable=self.icehalfDefText, anchor=W).grid(row=9, column=7)
        self.iceoneDefText = StringVar()
        self.iceoneDefText.set("0")
        Label(defCovFrame, textvariable=self.iceoneDefText, anchor=W).grid(row=9, column=9)
        self.icetwoDefText = StringVar()
        self.icetwoDefText.set("0")
        Label(defCovFrame, textvariable=self.icetwoDefText, anchor=W).grid(row=9, column=11)
        self.icefourDefText = StringVar()
        self.icefourDefText.set("0")
        Label(defCovFrame, textvariable=self.icefourDefText, anchor=W).grid(row=9, column=13)

        Label(defCovFrame, text="Fighting", anchor=W).grid(row=10, column=1, pady=1)
        self.fightingzeroDefText = StringVar()
        self.fightingzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.fightingzeroDefText, anchor=W).grid(row=10, column=3)
        self.fightingquarterDefText = StringVar()
        self.fightingquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.fightingquarterDefText, anchor=W).grid(row=10,column=5)
        self.fightinghalfDefText = StringVar()
        self.fightinghalfDefText.set("0")
        Label(defCovFrame, textvariable=self.fightinghalfDefText, anchor=W).grid(row=10, column=7)
        self.fightingoneDefText = StringVar()
        self.fightingoneDefText.set("0")
        Label(defCovFrame, textvariable=self.fightingoneDefText, anchor=W).grid(row=10, column=9)
        self.fightingtwoDefText = StringVar()
        self.fightingtwoDefText.set("0")
        Label(defCovFrame, textvariable=self.fightingtwoDefText, anchor=W).grid(row=10, column=11)
        self.fightingfourDefText = StringVar()
        self.fightingfourDefText.set("0")
        Label(defCovFrame, textvariable=self.fightingfourDefText, anchor=W).grid(row=10, column=13)

        Label(defCovFrame, text="Poison", anchor=W).grid(row=11, column=1, pady=1)
        self.poisonzeroDefText = StringVar()
        self.poisonzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.poisonzeroDefText, anchor=W).grid(row=11, column=3)
        self.poisonquarterDefText = StringVar()
        self.poisonquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.poisonquarterDefText, anchor=W).grid(row=11,column=5)
        self.poisonhalfDefText = StringVar()
        self.poisonhalfDefText.set("0")
        Label(defCovFrame, textvariable=self.poisonhalfDefText, anchor=W).grid(row=11, column=7)
        self.poisononeDefText = StringVar()
        self.poisononeDefText.set("0")
        Label(defCovFrame, textvariable=self.poisononeDefText, anchor=W).grid(row=11, column=9)
        self.poisontwoDefText = StringVar()
        self.poisontwoDefText.set("0")
        Label(defCovFrame, textvariable=self.poisontwoDefText, anchor=W).grid(row=11, column=11)
        self.poisonfourDefText = StringVar()
        self.poisonfourDefText.set("0")
        Label(defCovFrame, textvariable=self.poisonfourDefText, anchor=W).grid(row=11, column=13)

        Label(defCovFrame, text="Ground", anchor=W).grid(row=12, column=1, pady=1)
        self.groundzeroDefText = StringVar()
        self.groundzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.groundzeroDefText, anchor=W).grid(row=12, column=3)
        self.groundquarterDefText = StringVar()
        self.groundquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.groundquarterDefText, anchor=W).grid(row=12,column=5)
        self.groundhalfDefText = StringVar()
        self.groundhalfDefText.set("0")
        Label(defCovFrame, textvariable=self.groundhalfDefText, anchor=W).grid(row=12, column=7)
        self.groundoneDefText = StringVar()
        self.groundoneDefText.set("0")
        Label(defCovFrame, textvariable=self.groundoneDefText, anchor=W).grid(row=12, column=9)
        self.groundtwoDefText = StringVar()
        self.groundtwoDefText.set("0")
        Label(defCovFrame, textvariable=self.groundtwoDefText, anchor=W).grid(row=12, column=11)
        self.groundfourDefText = StringVar()
        self.groundfourDefText.set("0")
        Label(defCovFrame, textvariable=self.groundfourDefText, anchor=W).grid(row=12, column=13)

        Label(defCovFrame, text="Flying", anchor=W).grid(row=13, column=1, pady=1)
        self.flyingzeroDefText = StringVar()
        self.flyingzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.flyingzeroDefText, anchor=W).grid(row=13, column=3)
        self.flyingquarterDefText = StringVar()
        self.flyingquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.flyingquarterDefText, anchor=W).grid(row=13,column=5)
        self.flyinghalfDefText = StringVar()
        self.flyinghalfDefText.set("0")
        Label(defCovFrame, textvariable=self.flyinghalfDefText, anchor=W).grid(row=13, column=7)
        self.flyingoneDefText = StringVar()
        self.flyingoneDefText.set("0")
        Label(defCovFrame, textvariable=self.flyingoneDefText, anchor=W).grid(row=13, column=9)
        self.flyingtwoDefText = StringVar()
        self.flyingtwoDefText.set("0")
        Label(defCovFrame, textvariable=self.flyingtwoDefText, anchor=W).grid(row=13, column=11)
        self.flyingfourDefText = StringVar()
        self.flyingfourDefText.set("0")
        Label(defCovFrame, textvariable=self.flyingfourDefText, anchor=W).grid(row=13, column=13)

        Label(defCovFrame, text="Psychic", anchor=W).grid(row=14, column=1, pady=1)
        self.psychiczeroDefText = StringVar()
        self.psychiczeroDefText.set("0")
        Label(defCovFrame, textvariable=self.psychiczeroDefText, anchor=W).grid(row=14, column=3)
        self.psychicquarterDefText = StringVar()
        self.psychicquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.psychicquarterDefText, anchor=W).grid(row=14,column=5)
        self.psychichalfDefText = StringVar()
        self.psychichalfDefText.set("0")
        Label(defCovFrame, textvariable=self.psychichalfDefText, anchor=W).grid(row=14, column=7)
        self.psychiconeDefText = StringVar()
        self.psychiconeDefText.set("0")
        Label(defCovFrame, textvariable=self.psychiconeDefText, anchor=W).grid(row=14, column=9)
        self.psychictwoDefText = StringVar()
        self.psychictwoDefText.set("0")
        Label(defCovFrame, textvariable=self.psychictwoDefText, anchor=W).grid(row=14, column=11)
        self.psychicfourDefText = StringVar()
        self.psychicfourDefText.set("0")
        Label(defCovFrame, textvariable=self.psychicfourDefText, anchor=W).grid(row=14, column=13)

        Label(defCovFrame, text="Bug", anchor=W).grid(row=15, column=1, pady=1)
        self.bugzeroDefText = StringVar()
        self.bugzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.bugzeroDefText, anchor=W).grid(row=15, column=3)
        self.bugquarterDefText = StringVar()
        self.bugquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.bugquarterDefText, anchor=W).grid(row=15,column=5)
        self.bughalfDefText = StringVar()
        self.bughalfDefText.set("0")
        Label(defCovFrame, textvariable=self.bughalfDefText, anchor=W).grid(row=15, column=7)
        self.bugoneDefText = StringVar()
        self.bugoneDefText.set("0")
        Label(defCovFrame, textvariable=self.bugoneDefText, anchor=W).grid(row=15, column=9)
        self.bugtwoDefText = StringVar()
        self.bugtwoDefText.set("0")
        Label(defCovFrame, textvariable=self.bugtwoDefText, anchor=W).grid(row=15, column=11)
        self.bugfourDefText = StringVar()
        self.bugfourDefText.set("0")
        Label(defCovFrame, textvariable=self.bugfourDefText, anchor=W).grid(row=15, column=13)

        Label(defCovFrame, text="Rock", anchor=W).grid(row=16, column=1, pady=1)
        self.rockzeroDefText = StringVar()
        self.rockzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.rockzeroDefText, anchor=W).grid(row=16, column=3)
        self.rockquarterDefText = StringVar()
        self.rockquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.rockquarterDefText, anchor=W).grid(row=16,column=5)
        self.rockhalfDefText = StringVar()
        self.rockhalfDefText.set("0")
        Label(defCovFrame, textvariable=self.rockhalfDefText, anchor=W).grid(row=16, column=7)
        self.rockoneDefText = StringVar()
        self.rockoneDefText.set("0")
        Label(defCovFrame, textvariable=self.rockoneDefText, anchor=W).grid(row=16, column=9)
        self.rocktwoDefText = StringVar()
        self.rocktwoDefText.set("0")
        Label(defCovFrame, textvariable=self.rocktwoDefText, anchor=W).grid(row=16, column=11)
        self.rockfourDefText = StringVar()
        self.rockfourDefText.set("0")
        Label(defCovFrame, textvariable=self.rockfourDefText, anchor=W).grid(row=16, column=13)

        Label(defCovFrame, text="Ghost", anchor=W).grid(row=17, column=1, pady=1)
        self.ghostzeroDefText = StringVar()
        self.ghostzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.ghostzeroDefText, anchor=W).grid(row=17, column=3)
        self.ghostquarterDefText = StringVar()
        self.ghostquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.ghostquarterDefText, anchor=W).grid(row=17,column=5)
        self.ghosthalfDefText = StringVar()
        self.ghosthalfDefText.set("0")
        Label(defCovFrame, textvariable=self.ghosthalfDefText, anchor=W).grid(row=17, column=7)
        self.ghostoneDefText = StringVar()
        self.ghostoneDefText.set("0")
        Label(defCovFrame, textvariable=self.ghostoneDefText, anchor=W).grid(row=17, column=9)
        self.ghosttwoDefText = StringVar()
        self.ghosttwoDefText.set("0")
        Label(defCovFrame, textvariable=self.ghosttwoDefText, anchor=W).grid(row=17, column=11)
        self.ghostfourDefText = StringVar()
        self.ghostfourDefText.set("0")
        Label(defCovFrame, textvariable=self.ghostfourDefText, anchor=W).grid(row=17, column=13)

        Label(defCovFrame, text="Dragon", anchor=W).grid(row=18, column=1, pady=1)
        self.dragonzeroDefText = StringVar()
        self.dragonzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.dragonzeroDefText, anchor=W).grid(row=18, column=3)
        self.dragonquarterDefText = StringVar()
        self.dragonquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.dragonquarterDefText, anchor=W).grid(row=18,column=5)
        self.dragonhalfDefText = StringVar()
        self.dragonhalfDefText.set("0")
        Label(defCovFrame, textvariable=self.dragonhalfDefText, anchor=W).grid(row=18, column=7)
        self.dragononeDefText = StringVar()
        self.dragononeDefText.set("0")
        Label(defCovFrame, textvariable=self.dragononeDefText, anchor=W).grid(row=18, column=9)
        self.dragontwoDefText = StringVar()
        self.dragontwoDefText.set("0")
        Label(defCovFrame, textvariable=self.dragontwoDefText, anchor=W).grid(row=18, column=11)
        self.dragonfourDefText = StringVar()
        self.dragonfourDefText.set("0")
        Label(defCovFrame, textvariable=self.dragonfourDefText, anchor=W).grid(row=18, column=13)

        Label(defCovFrame, text="Dark", anchor=W).grid(row=19, column=1, pady=1)
        self.darkzeroDefText = StringVar()
        self.darkzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.darkzeroDefText, anchor=W).grid(row=19, column=3)
        self.darkquarterDefText = StringVar()
        self.darkquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.darkquarterDefText, anchor=W).grid(row=19,column=5)
        self.darkhalfDefText = StringVar()
        self.darkhalfDefText.set("0")
        Label(defCovFrame, textvariable=self.darkhalfDefText, anchor=W).grid(row=19, column=7)
        self.darkoneDefText = StringVar()
        self.darkoneDefText.set("0")
        Label(defCovFrame, textvariable=self.darkoneDefText, anchor=W).grid(row=19, column=9)
        self.darktwoDefText = StringVar()
        self.darktwoDefText.set("0")
        Label(defCovFrame, textvariable=self.darktwoDefText, anchor=W).grid(row=19, column=11)
        self.darkfourDefText = StringVar()
        self.darkfourDefText.set("0")
        Label(defCovFrame, textvariable=self.darkfourDefText, anchor=W).grid(row=19, column=13)

        Label(defCovFrame, text="Steel", anchor=W).grid(row=20, column=1, pady=1)
        self.steelzeroDefText = StringVar()
        self.steelzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.steelzeroDefText, anchor=W).grid(row=20, column=3)
        self.steelquarterDefText = StringVar()
        self.steelquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.steelquarterDefText, anchor=W).grid(row=20,column=5)
        self.steelhalfDefText = StringVar()
        self.steelhalfDefText.set("0")
        Label(defCovFrame, textvariable=self.steelhalfDefText, anchor=W).grid(row=20, column=7)
        self.steeloneDefText = StringVar()
        self.steeloneDefText.set("0")
        Label(defCovFrame, textvariable=self.steeloneDefText, anchor=W).grid(row=20, column=9)
        self.steeltwoDefText = StringVar()
        self.steeltwoDefText.set("0")
        Label(defCovFrame, textvariable=self.steeltwoDefText, anchor=W).grid(row=20, column=11)
        self.steelfourDefText = StringVar()
        self.steelfourDefText.set("0")
        Label(defCovFrame, textvariable=self.steelfourDefText, anchor=W).grid(row=20, column=13)

        Label(defCovFrame, text="Fairy", anchor=W).grid(row=21, column=1, pady=1)
        self.fairyzeroDefText = StringVar()
        self.fairyzeroDefText.set("0")
        Label(defCovFrame, textvariable=self.fairyzeroDefText, anchor=W).grid(row=21, column=3)
        self.fairyquarterDefText = StringVar()
        self.fairyquarterDefText.set("0")
        Label(defCovFrame, textvariable=self.fairyquarterDefText, anchor=W).grid(row=21,column=5)
        self.fairyhalfDefDefText = StringVar()
        self.fairyhalfDefDefText.set("0")
        Label(defCovFrame, textvariable=self.fairyhalfDefDefText, anchor=W).grid(row=21, column=7)
        self.fairyoneDefText = StringVar()
        self.fairyoneDefText.set("0")
        Label(defCovFrame, textvariable=self.fairyoneDefText, anchor=W).grid(row=21, column=9)
        self.fairytwoDefText = StringVar()
        self.fairytwoDefText.set("0")
        Label(defCovFrame, textvariable=self.fairytwoDefText, anchor=W).grid(row=21, column=11)
        self.fairyfourDefText = StringVar()
        self.fairyfourDefText.set("0")
        Label(defCovFrame, textvariable=self.fairyfourDefText, anchor=W).grid(row=21, column=13)

        Label(text="Counters").place(x=10, y=470)
        self.counterMssngr = Text(wrap=WORD)
        self.counterMssngr.place(x=10, y=490, width=250, height=190)
        #self.counterMssngr.config(state=DISABLED)
        counterscrollbar = Scrollbar(command=self.counterMssngr.yview)
        counterscrollbar.place(x=260, y=490, height=190)
        self.counterMssngr["yscrollcommand"] = counterscrollbar.set

        Label(text="Average Team Stats").place(x=350,y=470)
        Label(text="HP").place(x=305,y=495)
        Label(text="Atk").place(x=305,y=528)
        Label(text="Def").place(x=305,y=561)
        Label(text="SpA").place(x=305,y=594)
        Label(text="SpD").place(x=305,y=626)
        Label(text="Spe").place(x=305,y=660)
        self.averageHPCanvas = Canvas(width=150, height=20)
        self.averageHPCanvas.place(x=340,y=495)
        self.averageHPCanvas.create_rectangle(0, 0, 150, 20, fill="lawn green")
        self.averageAtkCanvas = Canvas(width=150, height=20)
        self.averageAtkCanvas.place(x=340,y=528)
        self.averageAtkCanvas.create_rectangle(0, 0, 150, 20, fill="lawn green")
        self.averageDefCanvas = Canvas(width=150, height=20)
        self.averageDefCanvas.place(x=340,y=561)
        self.averageDefCanvas.create_rectangle(0, 0, 150, 20, fill="lawn green")
        self.averageSpACanvas = Canvas(width=150, height=20)
        self.averageSpACanvas.place(x=340,y=594)
        self.averageSpACanvas.create_rectangle(0, 0, 150, 20, fill="lawn green")
        self.averageSpDCanvas = Canvas(width=150, height=20)
        self.averageSpDCanvas.place(x=340,y=626)
        self.averageSpDCanvas.create_rectangle(0, 0, 150, 20, fill="lawn green")
        self.averageSpeCanvas = Canvas(width=150, height=20)
        self.averageSpeCanvas.place(x=340,y=660)
        self.averageSpeCanvas.create_rectangle(0, 0, 150, 20, fill="lawn green")
        ttk.Separator(orient=VERTICAL).place(x=340, y=495, height=188)

        Label(text="Threats").place(x=805,y=470)
        self.threatMssngr = Text(wrap=WORD)
        self.threatMssngr.place(x=600,y=490,width=250,height=190)
        self.threatMssngr.config(state=DISABLED)
        threatscrollbar = Scrollbar(command=self.threatMssngr.yview)
        threatscrollbar.place(x=850, y=490,height=190)
        self.threatMssngr["yscrollcommand"] = threatscrollbar.set

root = Tk()
root.resizable(width=False, height=False)
TeamAnalyzer(root)
root.mainloop()
